version: "3.8"

services:
  db:
    image: mongo:latest
#    environment:             # pour l'initalisation de le bdd au premier d-c run
#      - MONGO_INITDB_ROOT_USERNAME
#      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - type: volume
        source: mydata
        target: /data/db
    networks:
      - mynetwork
    
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_PWD 
      - MONGO_USERNAME
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: ./src/
        target: /app/src/
    networks:
      - mynetwork

volumes:
  mydata:
    external: true

networks:
  mynetwork:
    name: mynetwork