version: "3.8"

services:
  db:
    image: mongo:latest
    volumes:
      - type: volume
        source: mydata
        target: /data/db
    networks:
      - mynetwork
    
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: ./src/
        target: /app/src/
    networks:
      - mynetwork

volumes:
  mydata:
    external: true

networks:
  mynetwork:
    name: mynetwork